FROM convert/base

WORKDIR /home/user

USER root
COPY R/install_pd.R .

ARG package
ENV PACKAGE=$package

ARG db
ENV DB=$db

RUN Rscript install_pd.R

VOLUME /home/user/data

COPY R/convert.R .
COPY R/custom_hthgu133pluspm.R .
COPY R/custom_htmg430a.R .

USER user

ENTRYPOINT []
